names = 'Harry ,Prashant'
length = len(names)
print(length)
print(names[0 : length : 1])
print(names[:])
print(names[::])
print(names[::-1])
print(names[::length-1])
print(names[::])
print(names[:5])
print(names[:-10])
print(names[:length-10])
print(names[7:])
print(names[-8: ])
print(names[length-8: ])
print(names[3:-3])
print(names[:-1]+names[-1:])